type Resident {
    id: ID!
    name: String
    first_name: String!
    middle_name: String
    last_name: String!
    suffix: String
    birthdate: DateTime
    gender: String!
    civil_status: String!
    citizenship: String!
    phone: String
    email: String
    user: User @hasOne
    barangay: Barangay @belongsTo
    household: Household @belongsTo
    purok: Purok @belongsTo
    blotters: Blotter @hasMany
    officials: Official @hasMany
    documents: Document @hasMany
    created_at: DateTime!
    updated_at: DateTime!
}

input ResidentInput {
    id: ID
    first_name: String
    middle_name: String
    last_name: String
    suffix: String
    birthdate: DateTime
    gender: String
    civil_status: String
    citizenship: String
    phone: String
    email: String
    barangay: ConnectBarangayRelation
    household: ConnectHouseholdRelation
    purok: ConnectPurokRelation
}

enum Gender {
    MALE @enum(value: "male")
    FEMALE @enum(value: "female")
}

enum CivilStatus {
    SINGLE @enum(value: "single")
    MARRIED @enum(value: "married")
    SEPARATED @enum(value: "separated")
    WIDOWED @enum(value: "widowed")
}

input ConnectResidentRelation {
    id: ID
    connect: ID
    upsert: ResidentInput
    delete: ID
}

input ConnectResidentsRelation {
    id: [ID]
    connect: [ID]
    sync: [ID]
    upsert: [ResidentInput]
    update: [ID]
    delete: [ID]
}

extend type Query {
    residents: [Resident]! @all
    residentsPaginate(
        first: Int!
        page: Int
        search: String @scope(name: "search")
        sort: SortInput @scope(name: "sort")
        filter: [FilterInput] @scope(name: "filter")
    ): [Resident]! @paginate
    residentsCount: Int! @count(model: "Resident")
}

extend type Mutation @guard {
    upsertResident(input: ResidentInput! @spread): Resident! @upsert
    deleteResident(id: [ID!] @eq): [Resident] @delete
}
